inputs:
    fastq: "path/to/fastq/files"
    samplesheet: "path/to/samplesheet.csv"
    phenotype: "path/to/phenotypes.csv"
    models: "path/to/models.csv"
    region_model: "path/to/region-model.txt"
    panel: "path/to/panel.csv"
    cell_reference: "data/blood-cell-type-reference.csv.gz"

paths:
    genome: "path/to/genome/directory"
    output: "path/to/output/directory"

parameters:
    assembly: "hg19"
    region_size: 100
    
workflow:
    cores: 16
    jobs: 50

resources:
   light:
       cpus: 4
       mem_gb: 4
       time: "02:00:00"
   medium:
       cpus: 8
       mem_gb: 8
       time: "04:00:00"
   heavy:
       cpus: 16
       mem_gb: 16
       time: "08:00:00"

containers:
    wgbs:
        image_url: "oras://docker.io/matthewsuderman/methylhead-wgbs"
        image_file: "methylhead-wgbs.sif"
        bin_dir: "/opt/conda/bin"
    meth:
        image_url: "oras://docker.io/matthewsuderman/methylhead-meth"
        image_file: "methylhead-meth.sif"
        bin_dir: "/usr/local/bin"
    qc:
        image_url: "oras://docker.io/matthewsuderman/methylhead-qc"
        image_file: "methylhead-qc.sif"
        bin_dir: "/usr/local/bin"

