name: dnam_lung_cancer_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - bcftools=1.10
  - bedtools=2.31.1
  - bismark=0.24.2
  - bowtie2=2.3.5.1
  - bwa=0.7.18
  - bwameth=0.2.7
  - fastqc=0.12.1
  - hisat2=2.2.0
  - multiqc=1.21
  - methyldackel=0.6.1
  - nextflow=23.10.1
  - perl=5.32.1
  - picard=2.18.23
  - qt=5.6.3
  - sambamba=1.0
  - samtools=1.18
  - trim-galore=0.6.10
  - trimmomatic=0.39
  - python-isal
  - pip
  - pip:
      - multiqc

