name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4            # clone repo
      - uses: nf-core/setup-nextflow@v2      # Java + Nextflow
        with:
          nextflow-version: '23.10.0'
      - uses: eWaterCycle/setup-apptainer@v2 # Apptainer
        with:
          apptainer-version: '1.1.9'
      - name: Run demo
        run: nextflow -C nextflow-test.config run main.nf
